### ISSUE TITLE
7z and 'Extracting' not recognized as an internal or external command and can not find path errors.

### ISSUE THREAD

**Issue by JR3535** [HHonzik/AddServerToPrism#1]
Prism Launch Instances folder is: instances ... checking for instances
The system cannot find the file specified.
Enter the name of your server (if not specified using DummyServer):
A subdirectory or file instances\DummyServer already exists.
Note: You will need to select an account which will be used to run the server as it will default to the current selected account when its invalid...
A subdirectory or file instances\DummyServer\patches already exists.
A subdirectory or file instances\DummyServer\libraries already exists.
Now get the JAR file of the server (e.g. paper-1.20.4.jar) and drag the file into this terminal window. The file will be copied to the required folder.
Drag and drop JAR file here: C:\MineCraft\FabricMineCraftServer\fabric-server-mc.1.20.4-loader.0.15.7-launcher.1.0.0.jar
        1 file(s) copied.
The system cannot find the file specified.
Could Not Find C:\Users\MINECR~1\AppData\Local\Temp\net.minecraft.json
Found 7-Zip: C:\Program Files\7-Zip\ .
'Extracting' is not recognized as an internal or external command,
operable program or batch file.
'7z' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
The system cannot find the file specified.
Found Main-Class: ~12    .
Finding Main-Class value in net.minecraft.json...
FINDSTR: Cannot open instances\DummyServer\patches\net.minecraft.json
Old Main-Class value is: ~18,-2
Replacing Main-Class value with ~12    in net.minecraft.json...
Get-Content : Cannot find path 'C:\Users\MineCraft\Desktop\instances\DummyServer\patches\net.minecraft.json' because
it does not exist.
At line:1 char:2
+ (Get-Content 'instances\DummyServer\patches\net.minecraft.json') -rep ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\MineCr....minecraft.json:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Main-Class value replaced with ~12    in net.minecraft.json
Done.

**Comment by JR3535** [comment]
running below corrects the 7z issue. Must restart cmd line so reads in from path.
setx PATH "%PATH%;C:\Program Files\7-Zip\"

whats left for errors.
Prism Launch Instances folder is: instances ... checking for instances
File Not Found
The system cannot find the path specified.
Enter the name of your server (if not specified using DummyServer):
Note: You will need to select an account which will be used to run the server as it will default to the current selected account when its invalid...
The system cannot find the path specified.
The system cannot find the path specified.
Now get the JAR file of the server (e.g. paper-1.20.4.jar) and drag the file into this terminal window. The file will be copied to the required folder.
Drag and drop JAR file here: C:\MineCraft\FabricMineCraftServer\fabric-server-mc.1.20.4-loader.0.15.7-launcher.1.0.0.jar
        1 file(s) copied.
The system cannot find the file specified.
Could Not Find C:\Users\MINECR~1\AppData\Local\Temp\net.minecraft.json
Found 7-Zip: C:\Program Files\7-Zip\ .
'Extracting' is not recognized as an internal or external command,
operable program or batch file.

7-Zip 24.04 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-04-05


Scanning the drive for archives:
1 file, 156985 bytes (154 KiB)

Extracting archive: instances\DummyServer\libraries\customjar-1.jar
--
Path = instances\DummyServer\libraries\customjar-1.jar
Type = zip
Physical Size = 156985

Everything is Ok

Size:       146
Compressed: 156985
        1 file(s) copied.
Found Main-Class: net.fabricmc.installer.ServerLauncher    .
Finding Main-Class value in net.minecraft.json...
FINDSTR: Cannot open instances\DummyServer\patches\net.minecraft.json
Old Main-Class value is: ~18,-2
Replacing Main-Class value with net.fabricmc.installer.ServerLauncher    in net.minecraft.json...
Get-Content : Cannot find path 'C:\Users\MineCraft\Desktop\instances\DummyServer\patches\net.minecraft.json' because
it does not exist.
At line:1 char:2
+ (Get-Content 'instances\DummyServer\patches\net.minecraft.json') -rep ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\MineCr....minecraft.json:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Main-Class value replaced with net.fabricmc.installer.ServerLauncher    in net.minecraft.json
Done.
Press any key to continue . . .

**Comment by NotVibeCodedSlop** [comment]
You need to install 7-Zip first, then it will work.

**Comment by HHonzik** [comment]
And also input a valid instances folder and not a folder in your desktop as that causes it to not find the files it has to copy over to make the instance.
